# This workflow has the following steps:
# Linting all the newly created or updated JavaScript files between consecutive pushes and pull requests affecting the main branch

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './package.json'

      - name: Install dependencies
        run: npm install

      - name: Get list of changed files
        run: |
          files=$(git diff --name-only HEAD^ HEAD \
            | grep '\.js$' \
            | tr '\n' ' ')
          echo "FILES=$files" >> $GITHUB_ENV

      - name: Run linter on changed files
        run: |
          if [ -n "$FILES" ]; then
            npx eslint $FILES
          else
            echo "No JavaScript files changed"
          fi
